# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

#[[social]]
#identifier = "linkedin"
#name = "LinkedIn"
#url = "https://www.linkedin.com/in/robert-m-l-snapper-9249b110/"

#[social.params]
#icon = "brand-twitter"